---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
  attributes:
    java:
      jdk_version: 7
- name: debian-9.0
  run_list:
    - recipe[apt]
  attributes:
    java:
      jdk_version: 8

suites:
- name: webgoat
  run_list:
    - recipe[webgoat]
  attributes:
    webgoat:
      path: /opt/wg
      port: 8081
